name: bible_trivia
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  game_levels_scrolling_map: ^0.0.7
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  intl_phone_number_input: ^0.7.4
  http: ^0.13.3
  shared_preferences: ^2.0.11
  flutter_dotenv: ^5.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png




