name: bible_trivia
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  game_levels_scrolling_map: ^0.0.7
  google_sign_in: ^6.2.1
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.0.11
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_facebook_auth: ^7.1.1
  bcrypt: ^1.1.3

dependency_overrides:
  firebase_auth_platform_interface : ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/facebook.jpeg




