// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGd8D4UjOhuvvNLE35-ENiUeksiGqA9U',
    appId: '1:242728995309:web:4667e320f821686e397fe4',
    messagingSenderId: '242728995309',
    projectId: 'quiz-smm',
    authDomain: 'quiz-smm.firebaseapp.com',
    storageBucket: 'quiz-smm.appspot.com',
    measurementId: 'G-TBRR6RJVN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRJSIgrNM7Q0fwEelpV2h7OOnRwKOxhM',
    appId: '1:242728995309:android:1fe94662a9ef3897397fe4',
    messagingSenderId: '242728995309',
    projectId: 'quiz-smm',
    storageBucket: 'quiz-smm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHwXRWMrD08_2pUSrdtxg7TV-0YiotzTc',
    appId: '1:242728995309:ios:2f159abd77113030397fe4',
    messagingSenderId: '242728995309',
    projectId: 'quiz-smm',
    storageBucket: 'quiz-smm.appspot.com',
    androidClientId: '242728995309-ab4fcjb18gl917dqs0a462hlelclvu7o.apps.googleusercontent.com',
    iosClientId: '242728995309-g2g9h15g5ja7uasqi38lv3pm8oku9a1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleTrivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGd8D4UjOhuvvNLE35-ENiUeksiGqA9U',
    appId: '1:242728995309:web:97a2bf7548171352397fe4',
    messagingSenderId: '242728995309',
    projectId: 'quiz-smm',
    authDomain: 'quiz-smm.firebaseapp.com',
    storageBucket: 'quiz-smm.appspot.com',
    measurementId: 'G-S4RXG9V14G',
  );
}
